export const metadata = {
  title: "Add Product | Dashboard | Next Hero",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <h2>Add product</h2>
    </div>
  );
};

export default page;
