export const metadata = {
  title: "About | Next Hero",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div>
      <h2>About page</h2>
    </div>
  );
};

export default AboutPage;
