export const metadata = {
  title: "Profile | Next Hero",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <h2>Profile page</h2>
    </div>
  );
};

export default page;
