export const metadata = {
  title: "Dashboard | Next Hero",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }) => {
  return (
    <div>
      <div>Sidebar</div>
      {children}
    </div>
  );
};

export default DashboardLayout;
